title: Andy Liu # your name (or website title) here
logo: "/images/profilePicture.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced Accounts Receivable Team Lead with a demonstrated history of working in the medical device industry. 
  Highly curious, motivated individual, and a continual learner with a strong focus on problem solving. 
  Thru this, I was able teach myself how to code ( JavaScript, React JS, and TypeScript ) ,and applied problem solving techniques on the job and at home when coding for fun. 
  <br><br>
  I'm a web developer whose passionate about learning. Ever since I learned JavaScript, 
  I've been curious as to how far I can personally take this language to, and possbily pick up a new language or two in the future. 
  I would like to expand my knowledge of Javascript with IoT & Robotics. So far, biggest my long term robotics projects are my DJI Tello , 
  MBot, and PS4 Controller / XBox Controller. I find drones highly facinating, but as I grow as a web developer, I would also like to blend drones and the web together, 
  and explore possbilities.
  <br><br>
  <a href="https://www.linkedin.com/in/andy-liu-951b9413/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
